from .general import (
    BENCHMARKS,
    BENCHMARK_CURRENCIES,
    ANALYSIS_DATES,
    DOWNLOAD_DEFAULTS,
    YFINANCE_COLUMNS,
)

from .risk import (
    RISK_ANALYSIS,
    STATISTICAL_DEFAULTS,
    NUMERICAL_DEFAULTS,
    OPTIMIZATION_DEFAULTS,
    RATIO_INTERPRETATION,
    DRAWDOWN_RISK_LEVELS,
    SKEWNESS_THRESHOLDS,
    KURTOSIS_THRESHOLDS,
    SORTINO_THRESHOLDS,
    TRACKING_ERROR_THRESHOLDS,
    INFORMATION_RATIO_THRESHOLDS,
    BETA_THRESHOLDS,
    ALPHA_THRESHOLDS,
    VAR_RISK_LEVELS,
    NORMALITY_THRESHOLDS,
    ANDERSON_DARLING,
    TRACKING_ERROR_DEFAULTS,
    CORRELATION_REPORT,
)

from .capm import (
    CML_POINTS,
    CML_EXTENSION_FACTOR,
    SML_CONFIG,
    ALPHA_THRESHOLDS_IDENTIFICATION,
    MIN_WEIGHT_DISPLAY,
    TOP_ASSETS_DISPLAY,
)

from .valuation import (
    VALUATION_THRESHOLDS,
    SCORING_RANGES,
    SCORING_WEIGHTS,
    ALERT_THRESHOLDS,
    PROFITABILITY_SCORING_RANGES,
    FINANCIAL_HEALTH_SCORING,
    EFFICIENCY_SCORING,
    VALUATION_SCORING,
    GROWTH_SCORING_WEIGHTS,
    TRADING_SIGNAL_RULES,
    PRICE_TARGET_CONFIG,
    OVERALL_VALUATION_LOGIC,
    VALUATION_MULTIPLES_FALLBACKS,
    SECTOR_ANALYSIS_CONFIG,
    SECTOR_PEERS,
    REPORTING_CONFIG,
    SCORE_INTERPRETATION,
    SCORE_AGGREGATION_WEIGHTS,
    COMPANY_ANALYSIS_WEIGHTS,
    INVESTMENT_PROFILES,
    CONCLUSION_THRESHOLDS,
)

from .portfolio import (
    PORTFOLIO_CONFIG,
    TRADING_SIGNALS_CONFIG,
    INDEX_CONFIG,
)

from .optimizer import (
    OPTIMIZER_NUMERICAL,
    OPTIMIZER_BLACK_LITTERMAN,
)

__all__ = [
    'BENCHMARKS', 'BENCHMARK_CURRENCIES', 'ANALYSIS_DATES',
    'DOWNLOAD_DEFAULTS', 'YFINANCE_COLUMNS',
    'RISK_ANALYSIS', 'STATISTICAL_DEFAULTS', 'NUMERICAL_DEFAULTS',
    'OPTIMIZATION_DEFAULTS', 'RATIO_INTERPRETATION', 'DRAWDOWN_RISK_LEVELS',
    'SKEWNESS_THRESHOLDS', 'KURTOSIS_THRESHOLDS', 'SORTINO_THRESHOLDS',
    'TRACKING_ERROR_THRESHOLDS', 'INFORMATION_RATIO_THRESHOLDS',
    'BETA_THRESHOLDS', 'ALPHA_THRESHOLDS', 'VAR_RISK_LEVELS',
    'NORMALITY_THRESHOLDS', 'ANDERSON_DARLING', 'TRACKING_ERROR_DEFAULTS',
    'CORRELATION_REPORT',
    'CML_POINTS', 'CML_EXTENSION_FACTOR', 'SML_CONFIG',
    'ALPHA_THRESHOLDS_IDENTIFICATION', 'MIN_WEIGHT_DISPLAY', 'TOP_ASSETS_DISPLAY',
    'VALUATION_THRESHOLDS', 'SCORING_RANGES', 'SCORING_WEIGHTS',
    'ALERT_THRESHOLDS', 'PROFITABILITY_SCORING_RANGES', 'FINANCIAL_HEALTH_SCORING',
    'EFFICIENCY_SCORING', 'VALUATION_SCORING', 'GROWTH_SCORING_WEIGHTS',
    'TRADING_SIGNAL_RULES', 'PRICE_TARGET_CONFIG', 'OVERALL_VALUATION_LOGIC',
    'VALUATION_MULTIPLES_FALLBACKS', 'SECTOR_ANALYSIS_CONFIG', 'SECTOR_PEERS',
    'REPORTING_CONFIG', 'SCORE_INTERPRETATION', 'SCORE_AGGREGATION_WEIGHTS',
    'COMPANY_ANALYSIS_WEIGHTS', 'INVESTMENT_PROFILES', 'CONCLUSION_THRESHOLDS',
    'PORTFOLIO_CONFIG', 'TRADING_SIGNALS_CONFIG', 'INDEX_CONFIG',
    'OPTIMIZER_NUMERICAL', 'OPTIMIZER_BLACK_LITTERMAN',
    'ANNUAL_FACTOR', 'DEFAULT_CONFIDENCE_LEVEL',
    'MONTE_CARLO_SIMULATIONS', 'MONTE_CARLO_SEED', 'ROLLING_WINDOW',
    'SIGNIFICANCE_LEVEL', 'MIN_OBSERVATIONS', 'EPSILON',
    'OPTIMIZATION_METHOD', 'FRONTIER_POINTS',
    'ADJ_CLOSE_COL', 'CLOSE_COL',
    'ANALYSIS_START_DATE', 'ANALYSIS_END_DATE',
    'USE_CURRENT_DATE', 'ANALYSIS_LOOKBACK_YEARS',
    'DEFAULT_NA_SCORE',
]

ANNUAL_FACTOR = RISK_ANALYSIS['annual_factor']
DEFAULT_CONFIDENCE_LEVEL = RISK_ANALYSIS['default_confidence_level']
MONTE_CARLO_SIMULATIONS = RISK_ANALYSIS['monte_carlo']['n_simulations']
MONTE_CARLO_SEED = RISK_ANALYSIS['monte_carlo']['seed']
ROLLING_WINDOW = RISK_ANALYSIS['rolling']['default_window']

SIGNIFICANCE_LEVEL = STATISTICAL_DEFAULTS['significance_level']
MIN_OBSERVATIONS = STATISTICAL_DEFAULTS['min_observations']

EPSILON = NUMERICAL_DEFAULTS['epsilon']
OPTIMIZATION_METHOD = OPTIMIZATION_DEFAULTS['method']
FRONTIER_POINTS = OPTIMIZATION_DEFAULTS['frontier_points']

ADJ_CLOSE_COL = YFINANCE_COLUMNS['adj_close']
CLOSE_COL = YFINANCE_COLUMNS['close']

ANALYSIS_START_DATE = ANALYSIS_DATES['start_date']
ANALYSIS_END_DATE = ANALYSIS_DATES['end_date']
USE_CURRENT_DATE = ANALYSIS_DATES['use_current_date_as_end']
ANALYSIS_LOOKBACK_YEARS = ANALYSIS_DATES['default_lookback_years']

DEFAULT_NA_SCORE = SCORE_INTERPRETATION['default_na_score']
